PREFIX salt: <http://slobr.linkedmusic.org/salt/>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>

SELECT DISTINCT ?uri ?appellation ?startdate ?enddate WHERE {{
    {0}
    ?uri salt:in_saltset <http://slobr.linkedmusic.org/saltsets/ash_places> .
    OPTIONAL {{
        ?uri crm:P1_is_identified_by ?appeluri .
        ?appeluri rdfs:label ?appellation .
        ?production crm:P7_took_place_at ?uri .
        ?production crm:P4_has_time-span ?timespan .
        ?timespan crm:P82a_begin_of_the_begin ?startdate .
        ?timespan crm:P82b_end_of_the_end ?enddate
    }}
}}
